name: "Build Docker Image"

inputs:
  image:
    required: true
  context:
    required: false
  tags:
    required: false
  registry:
    required: false
  username:
    required: true
  password:
    required: true
  stage:
    required: false

outputs:
  image-id:
    description: The ID of the image that was built
    value: ${{ steps.build.outputs.imageid }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Context for Buildx
      run: docker context create builder

    # https://github.com/docker/setup-buildx-action/issues/105
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builder

    - name: Generate metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: "type=sha,${{ inputs.tags }}"

    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - id: build
      name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        target: ${{ inputs.stage }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=registry,ref=${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
