name: "Build Docker Image"
inputs:
  image:
    required: true
  context:
    required: false
    default: "."
  tags:
    default: ""
    required: false
  registry:
    required: false
    default: docker.io
  username:
    required: false
  password:
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: "type=sha,${{ inputs.tags }}"

    - name: Login
      if: ${{ inputs.push }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        load: true
        cache-from: type=registry,ref=${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
