name: "Build Docker Image"
inputs:
  image:
    required: true
    description: The image name
  context:
    required: false
    default: "."
  tags:
    default: ""
    required: false
  push:
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: "type=sha,${{ inputs.tags }}"

    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ inputs.push }}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar

    - name: Generate artifact name
      run: >
        echo 'ARTIFACT_NAME=${{ inputs. image }}'
        | sed 's%/%-%g'
        >>$GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: /tmp/image.tar
        if-no-files-found: error
