name: Setup docker

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Context for Buildx
      shell: bash
      run: |
        docker context create buildx
        docker context use buildx

    # https://github.com/docker/setup-buildx-action/issues/105
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: kubernetes
        endpoint: buildx
