name: Bump Version, Build and Release

inputs:
  token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      shell: bash
      with:
        python-version: 3.x

    - name: Install bump2version
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install bump2version

    - name: Configure git
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Bump version
      shell: bash
      run: |
        bump2version patch --tag --verbose

    - name: Push changes
      uses: ad-m/github-push-action@master
      shell: bash
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ github.ref }}
        tags: true
