name: Deploy QA

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      application:
        required: true
        type: string
      namespace:
        required: true
        type: string
      image:
        required: true
        type: string
      repository:
        required: false
        type: string
        default: cern-sis/kubernetes
      new_tag:
        required: false
        type: string
      new_digest:
        required: false
        type: string
    secrets:
      PAT:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      if: ${{ github.event_name == 'push' && inputs.new_tag}}
      with:
        repository: ${{ inputs.repository }}
        event-type: deploy
        token: ${{ secrets.PAT }}
        client-payload: '{"project":"${{ inputs.project }}", "application":"${{ inputs.application }}", "namespace":"${{ inputs.namespace }}", "image":"${{ inputs.image }}","new_tag":"${{ inputs.new_tag }}"}'

    - uses: peter-evans/repository-dispatch@v1
      if: ${{ github.event_name == 'push' && inputs.new_digest}}
      with:
        repository: ${{ inputs.repository }}
        event-type: deploy
        token: ${{ secrets.PAT }}
        client-payload: '{"project":"${{ inputs.project }}", "application":"${{ inputs.application }}", "namespace":"${{ inputs.namespace }}", "image":"${{ inputs.image }}","new_digest":"${{ inputs.new_digest }}"}'
